# Default values for fluid.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

workdir: /tmp

dataset:
  controller:
    image: registry.cn-hangzhou.aliyuncs.com/fluid/dataset-controller:v0.6.0-2609794

csi:
  registrar:
    image: registry.cn-hangzhou.aliyuncs.com/acs/csi-node-driver-registrar:v1.2.0
  plugins:
    image: registry.cn-hangzhou.aliyuncs.com/fluid/fluid-csi:v0.6.0-2609794
  kubelet:
    rootDir: /var/lib/kubelet

runtime:
  mountRoot: /runtime-mnt
  alluxio:
    enabled: true
    init:
      image: registry.cn-hangzhou.aliyuncs.com/fluid/init-users:v0.6.0-2609794
    controller:
      image: registry.cn-hangzhou.aliyuncs.com/fluid/alluxioruntime-controller:v0.6.0-2609794
    runtime:
      image: registry.cn-huhehaote.aliyuncs.com/alluxio/alluxio:release-2.5.0-1-SNAPSHOT-cb60e05
    fuse:
      image: registry.cn-huhehaote.aliyuncs.com/alluxio/alluxio-fuse:release-2.5.0-1-SNAPSHOT-cb60e05
  jindo:
    enabled: false
    smartdata:
      image: registry.cn-shanghai.aliyuncs.com/jindofs/smartdata:3.5.2
    fuse:
      image: registry.cn-shanghai.aliyuncs.com/jindofs/jindo-fuse:3.5.2
    controller:
      image: registry.cn-hangzhou.aliyuncs.com/fluid/jindoruntime-controller:v0.6.0-2609794
