# Default values for fluid.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

dataset:
  controller:
    image: registry.cn-hangzhou.aliyuncs.com/fluid/dataset-controller:v0.5.0-569c39b

csi:
  registrar:
    image: registry.cn-hangzhou.aliyuncs.com/acs/csi-node-driver-registrar:v1.2.0
  plugins:
    image: registry.cn-hangzhou.aliyuncs.com/fluid/fluid-csi:v0.5.0-569c39b

runtime:
  mountRoot: /runtime-mnt
  alluxio:
    enabled: true
    init:
      image: registry.cn-hangzhou.aliyuncs.com/fluid/init-users:v0.5.0-569c39b
    controller:
      image: registry.cn-hangzhou.aliyuncs.com/fluid/alluxioruntime-controller:v0.5.0-569c39b
    runtime:
      image: registry.cn-huhehaote.aliyuncs.com/alluxio/alluxio:2.3.0-SNAPSHOT-985b84c
    fuse:
      image: registry.cn-huhehaote.aliyuncs.com/alluxio/alluxio-fuse:2.3.0-SNAPSHOT-985b84c
    dataload:
      image: registry.cn-huhehaote.aliyuncs.com/alluxio/alluxio:2.3.0-SNAPSHOT-985b84c
  jindo:
    enabled: true
    controller:
      image: registry.cn-hangzhou.aliyuncs.com/fluid/jindoruntime-controller:v0.5.0-569c39b
