# Default values for fluid.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

controller:
  image: registry.cn-hangzhou.aliyuncs.com/fluid/runtime-controller:v0.4.0-873197c


csi:
  registrar:
    image: registry.cn-hangzhou.aliyuncs.com/acs/csi-node-driver-registrar:v1.2.0
  plugins:
    image: registry.cn-hangzhou.aliyuncs.com/fluid/fluid-csi:v0.4.0-873197c

runtime:
  mountRoot: /alluxio-mnt
  alluxio:
    initImage: registry.cn-hangzhou.aliyuncs.com/fluid/init-users:v0.4.0-873197c
