# Default values for fluid.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

workdir: /tmp

dataset:
  controller:
    image: fluidcloudnative/dataset-controller:v0.7.0-e94a6af

csi:
  recoverFusePeriod: -1
  config:
    hostNetwork: false
  registrar:
    image: registry.aliyuncs.com/acs/csi-node-driver-registrar:v1.2.0
  plugins:
    image: fluidcloudnative/fluid-csi:v0.7.0-e94a6af
  kubelet:
    rootDir: /var/lib/kubelet

runtime:
  criticalFusePod: true
  syncRetryDuration: 15s
  mountRoot: /runtime-mnt
  alluxio:
    runtimeWorkers: 3
    portRange: 20000-26000
    enabled: true
    init:
      image: fluidcloudnative/init-users:v0.7.0-e94a6af
    controller:
      image: fluidcloudnative/alluxioruntime-controller:v0.7.0-e94a6af
    runtime:
      image: registry.aliyuncs.com/alluxio/alluxio:release-2.7.2-SNAPSHOT-3714f2b
    fuse:
      image: registry.aliyuncs.com/alluxio/alluxio-fuse:release-2.7.2-SNAPSHOT-3714f2b
  jindo:
    runtimeWorkers: 3
    portRange: 18000-19999
    enabled: false
    smartdata:
      image: registry.cn-shanghai.aliyuncs.com/jindofs/smartdata:3.8.0
    fuse:
      image: registry.cn-shanghai.aliyuncs.com/jindofs/jindo-fuse:3.8.0
    controller:
      image: fluidcloudnative/jindoruntime-controller:v0.7.0-e94a6af
    init:
      portCheck:
        enabled: false
      image: fluidcloudnative/init-users:v0.7.0-e94a6af
  goosefs:
    runtimeWorkers: 3
    portRange: 26000-32000
    enabled: false
    init:
      image: fluidcloudnative/init-users:v0.7.0-e94a6af
    controller:
      image: fluidcloudnative/goosefsruntime-controller:v0.7.0-e94a6af
    runtime:
      image: ccr.ccs.tencentyun.com/qcloud/goosefs:v1.1.0-kona_jdk11 
    fuse:
      image: ccr.ccs.tencentyun.com/qcloud/goosefs:v1.1.0-kona_jdk11 
  juicefs:
    enabled: false
    controller:
      image: fluidcloudnative/juicefsruntime-controller:v0.7.0-e94a6af
    fuse:
      image: juicedata/juicefs-csi-driver:v0.11.0

webhook:
  enabled: true
  image: fluidcloudnative/fluid-webhook:v0.7.0-e94a6af
  replicas: 1

