# Default values for fluid.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

workdir: /tmp
crdUpgrade:
  image: fluidcloudnative/fluid-crd-upgrader:v0.9.0-e503877

image:
  imagePullSecrets: []

dataset:
  replicas: 1
  controller:
    image: fluidcloudnative/dataset-controller:v0.9.0-e503877

csi:
  featureGates: "FuseRecovery=false"
  config:
    hostNetwork: false
  registrar:
    image: registry.aliyuncs.com/acs/csi-node-driver-registrar:v2.3.0-038aeb6-aliyun
  plugins:
    image: fluidcloudnative/fluid-csi:v0.9.0-e503877
  kubelet:
    rootDir: /var/lib/kubelet
  pruneFs: fuse.alluxio-fuse,fuse.jindofs-fuse,fuse.juicefs,fuse.goosefs-fuse,ossfs

runtime:
  criticalFusePod: true
  syncRetryDuration: 15s
  mountRoot: /runtime-mnt
  alluxio:
    replicas: 1
    runtimeWorkers: 3
    portRange: 20000-26000
    portAllocatePolicy: bitmap
    enabled: false
    init:
      image: fluidcloudnative/init-users:v0.9.0-e503877
    controller:
      image: fluidcloudnative/alluxioruntime-controller:v0.9.0-e503877
    runtime:
      image: alluxio/alluxio-dev:2.9.0
    fuse:
      image: alluxio/alluxio-dev:2.9.0
  jindo:
    replicas: 1
    runtimeWorkers: 3
    portRange: 18000-19999
    enabled: false
    engine: jindofsx
    queryUfsTotal: true
    smartdata:
      image: registry.cn-shanghai.aliyuncs.com/jindofs/smartdata:4.5.2
    fuse:
      image: registry.cn-shanghai.aliyuncs.com/jindofs/jindo-fuse:4.5.2
    controller:
      image: fluidcloudnative/jindoruntime-controller:v0.9.0-e503877
    init:
      portCheck:
        enabled: false
      image: fluidcloudnative/init-users:v0.9.0-e503877
  goosefs:
    replicas: 1
    runtimeWorkers: 3
    portRange: 26000-32000
    enabled: false
    init:
      image: fluidcloudnative/init-users:v0.9.0-e503877
    controller:
      image: fluidcloudnative/goosefsruntime-controller:v0.9.0-e503877
    runtime:
      image: ccr.ccs.tencentyun.com/qcloud/goosefs:v1.2.0
    fuse:
      image: ccr.ccs.tencentyun.com/qcloud/goosefs-fuse:v1.2.0
  juicefs:
    replicas: 1
    enabled: false
    controller:
      image: fluidcloudnative/juicefsruntime-controller:v0.9.0-e503877
    fuse:
      image: juicedata/juicefs-fuse:v1.0.0-4.8.0
  thin:
    replicas: 1
    enabled: false
    controller:
      image: fluidcloudnative/thinruntime-controller:v0.9.0-e503877
  eac:
    replicas: 1
    enabled: false
    controller:
      image:
      imagePullPolicy: Always
    init:
      image:
    master:
      image:
    worker:
      image:
    fuse:
      image:

webhook:
  enabled: true
  image: fluidcloudnative/fluid-webhook:v0.9.0-e503877
  replicas: 1

fluidapp:
  enabled: true
  replicas: 1
  controller:
    image: fluidcloudnative/application-controller:v0.9.0-e503877
