# Default values for fluid.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

workdir: /tmp

dataset:
  controller:
    image: fluidcloudnative/dataset-controller:v0.8.0-4f14ed7

csi:
  featureGates: "FuseRecovery=false"
  config:
    hostNetwork: false
  registrar:
    image: registry.aliyuncs.com/acs/csi-node-driver-registrar:v1.2.0
  plugins:
    image: fluidcloudnative/fluid-csi:v0.8.0-4f14ed7
  kubelet:
    rootDir: /var/lib/kubelet

runtime:
  criticalFusePod: true
  syncRetryDuration: 15s
  mountRoot: /runtime-mnt
  alluxio:
    runtimeWorkers: 3
    portRange: 20000-26000
    enabled: true
    init:
      image: fluidcloudnative/init-users:v0.8.0-4f14ed7
    controller:
      image: fluidcloudnative/alluxioruntime-controller:v0.8.0-4f14ed7
    runtime:
      # image: fluidcloudnative/alluxio:release-2.7.3-SNAPSHOT-a7154f1
      image: fluidcloudnative/alluxio:release-2.8.1-SNAPSHOT-0433ade
    fuse:
      # image: fluidcloudnative/alluxio-fuse:release-2.7.3-SNAPSHOT-a7154f1
      image: fluidcloudnative/alluxio-fuse:release-2.8.1-SNAPSHOT-0433ade
  jindo:
    runtimeWorkers: 3
    portRange: 18000-19999
    enabled: false
    engine: jindofsx
    smartdata:
      image: registry.cn-shanghai.aliyuncs.com/jindofs/smartdata:3.8.0
    fuse:
      image: registry.cn-shanghai.aliyuncs.com/jindofs/jindo-fuse:3.8.0
    controller:
      image: fluidcloudnative/jindoruntime-controller:v0.8.0-4f14ed7
    init:
      portCheck:
        enabled: false
      image: fluidcloudnative/init-users:v0.8.0-4f14ed7
  goosefs:
    runtimeWorkers: 3
    portRange: 26000-32000
    enabled: false
    init:
      image: fluidcloudnative/init-users:v0.8.0-4f14ed7
    controller:
      image: fluidcloudnative/goosefsruntime-controller:v0.8.0-4f14ed7
    runtime:
      image: ccr.ccs.tencentyun.com/qcloud/goosefs:v1.2.0
    fuse:
      image: ccr.ccs.tencentyun.com/qcloud/goosefs-fuse:v1.2.0
  juicefs:
    enabled: false
    controller:
      image: fluidcloudnative/juicefsruntime-controller:v0.8.0-4f14ed7
    fuse:
      image: registry.cn-hangzhou.aliyuncs.com/juicefs/juicefs-fuse:v1.0.0-beta2

webhook:
  enabled: true
  image: fluidcloudnative/fluid-webhook:v0.8.0-4f14ed7
  replicas: 1

fluidapp:
  enabled: true
  controller:
    image: fluidcloudnative/application-controller:v0.8.0-4f14ed7
