# Default values for fluid.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

workdir: /tmp

dataset:
  controller:
    image: registry.cn-hangzhou.aliyuncs.com/fluid/dataset-controller:v0.5.0-df9cd9b

csi:
  registrar:
    image: registry.cn-hangzhou.aliyuncs.com/acs/csi-node-driver-registrar:v1.2.0
  plugins:
    image: registry.cn-hangzhou.aliyuncs.com/fluid/fluid-csi:v0.5.0-df9cd9b
  kubelet:
    rootDir: /var/lib/kubelet

runtime:
  mountRoot: /runtime-mnt
  alluxio:
    enabled: true
    init:
      image: registry.cn-hangzhou.aliyuncs.com/fluid/init-users:v0.5.0-df9cd9b
    controller:
      image: registry.cn-hangzhou.aliyuncs.com/fluid/alluxioruntime-controller:v0.5.0-df9cd9b
    runtime:
      image: registry.cn-huhehaote.aliyuncs.com/alluxio/alluxio:2.4.1-2-SNAPSHOT-a6ee7e2
    fuse:
      image: registry.cn-huhehaote.aliyuncs.com/alluxio/alluxio-fuse:2.4.1-2-SNAPSHOT-a6ee7e2
  jindo:
    enabled: false
    controller:
      image: registry.cn-hangzhou.aliyuncs.com/fluid/jindoruntime-controller:v0.5.0-df9cd9b
