name: juicefs
apiVersion: v1
description: FileSystem aimed for data analytics and machine learning in any cloud.
version: 0.2.16
appVersion: v1.0.0
home: https://juicefs.com/
maintainers:
- name: Weiwei Zhu
  email: weiwei.zhu@juicedata.io
- name: Dongdong Lv
  email: lvdongdong30@gmail.com
