# This should not be modified in the usual case.
fullnameOverride: juicefs
edition: community

## Common ##

## global image pull secrets
imagePullSecrets: []

owner:
  enabled: false
  name: ""
  kind: ""
  uid: ""
  apiVersion: ""
  blockOwnerDeletion: false
  controller: false

##
## Example:
##   - key: "toleration=key"
##     operator: "Equal"
##     value: "value"
##     effect: "NoSchedule"
##
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []

tieredstore:
  path: /dev/shm

# Docker Image
image: juicedata/juicefs-fuse
imageTag: v1.0.0
imagePullPolicy: IfNotPresent

## WORKER ##
worker:
  image: ""
  imageTag: ""
  imagePullPolicy: ""
  nodeSelector: ""
  cacheDir: ""
  envs: []
  command: ""
  mountPath: /mnt/jfs
  statCmd: "stat -c %i /mnt/jfs"
  podManagementPolicy: Parallel
  hostNetwork: false
  resources:
    requests:
#      cpu: "0.5"
#      memory: "1G"
    limits:
#      cpu: "4"
#      memory: "4G"
  replicas: 0
  labels: {}
  annotations: {}
  volumes: []
  volumeMounts: []


configs:
  name: ""
  accesskeySecret: ""
  accesskeySecretKey: ""
  secretkeySecret: ""
  secretkeySecretKey: ""
  bucket: ""
  metaurlSecret: ""
  metaurlSecretKey: ""
  storage: ""
  tokenSecret: ""
  tokenSecretKey: ""
  formatCmd : ""
  quotaCmd: ""

## FUSE ##

fuse:
  hostNetwork: false
  subPath: ""
  criticalPod: false
  enabled: true
  image: juicedata/juicefs-csi-driver
  imageTag: v0.11.0
  imagePullPolicy: IfNotPresent
  envs: []
  nodeSelector: {}
  # Mount path in the host
  mountPath: /mnt/jfs
  cacheDir: ""
  hostMountPath: /mnt/jfs
  command: "/usr/local/bin/juicefs mount /mnt/jfs"
  statCmd: "stat -c %i /mnt/jfs"
  updateStrategy:
    type: OnDelete
  resources:
    requests:
#      cpu: "0.5"
#      memory: "1G"
    limits:
#      cpu: "4"
#      memory: "4G"
  labels: {}
  annotations: {}
  volumes: []
  volumeMounts: []

runtimeIdentity:
  namespace: default
  name: xxx
