{{- $masterCount := int .Values.master.replicaCount }}
{{- $isSingleMaster := eq $masterCount 1 }}
{{- $isRaftHa := eq $masterCount 3 }}

apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": before-hook-creation
  name: {{ template "jindofs.fullname" . }}-config
  labels:
    name: {{ template "jindofs.fullname" . }}-config
    app: {{ template "jindofs.name" . }}
    chart: {{ template "jindofs.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  ownerReferences:
  {{- if .Values.owner.enabled }}
  - apiVersion: {{ .Values.owner.apiVersion }}
    blockOwnerDeletion: {{ .Values.owner.blockOwnerDeletion }}
    controller: {{ .Values.owner.controller }}
    kind: {{ .Values.owner.kind }}
    name: {{ .Values.owner.name }}
    uid: {{ .Values.owner.uid }}
  {{- end }}
data:
  jindofsx.cfg: |
    [jindofsx-common]
    {{- range $key, $val := .Values.logConfig }}
    {{ $key }} = {{ $val }}
    {{- end }}
    {{- range $key, $val := .Values.master.secretProperties }}
    {{ $key }} = {{ $val }}
    {{- end }}
    {{- range $key, $val := .Values.master.fileStoreProperties }}
    {{ $key }} = {{ $val }}
    {{- end }}

    [jindofsx-storage]
    {{- range $key, $val := .Values.worker.properties }}
    {{ $key }} = {{ $val }}
    {{- end}}

    [jindofsx-namespace]
    {{- range $key, $val := .Values.master.properties }}
    {{ $key }} = {{ $val }}
    {{- end }}

  core-site.xml: |
    <?xml version="1.0"?>
    <configuration>
        <property>
            <name>fs.oss.impl</name>
            <value>com.aliyun.jindodata.oss.JindoOssFileSystem</value>
        </property>

        <property>
            <name>fs.AbstractFileSystem.oss.impl</name>
            <value>com.aliyun.jindodata.oss.OSS</value>
        </property>

        <property>
            <name>fs.jindo.impl</name>
            <value>com.aliyun.jindodata.jindo.JindoFileSystem</value>
        </property>

        <property>
            <name>fs.AbstractFileSystem.jindo.impl</name>
            <value>com.aliyun.jindodata.jindo.JINDO</value>
        </property>

        <property>
            <name>fs.xengine</name>
            <value>jindofsx</value>
        </property>
        {{- if $isSingleMaster }}
        <property>
            <name>fs.jindofsx.namespace.rpc.address</name>
            <value>{{ template "jindofs.fullname" . }}-master-0.{{ .Values.runtimeIdentity.namespace }}:{{ .Values.master.ports.rpc }}</value>
        </property>
        {{- else if $isRaftHa }}
        <property>
            <name>fs.jindofsx.namespace.rpc.address</name>
            <value>{{ template "jindofs.fullname" . }}-master-0.{{ .Values.runtimeIdentity.namespace }}:{{ .Values.master.ports.rpc }},{{ template "jindofs.fullname" . }}-master-1.{{ .Values.runtimeIdentity.namespace }}:{{ .Values.master.ports.rpc }},{{ template "jindofs.fullname" . }}-master-2.{{ .Values.runtimeIdentity.namespace }}:{{ .Values.master.ports.rpc }}</value>
        </property>
        {{- end }}
        {{- range $key, $val := .Values.fuse.properties }}
        <property>
            <name>{{ $key }}</name>
            <value>{{ $val }}</value>
        </property>
        {{- end}}
    </configuration>
  jindosdk.cfg: |
    [common]
    {{- range $key, $val := .Values.fuseLogConfig }}
    {{ $key }} = {{ $val }}
    {{- end }}
    {{- range $key, $val := .Values.master.secretProperties }}
    {{ $key }} = {{ $val }}
    {{- end }}

    [jindosdk]
    {{- if $isSingleMaster }}
    fs.jindofsx.namespace.rpc.address = {{ template "jindofs.fullname" . }}-master-0.{{ .Values.runtimeIdentity.namespace }}:{{ .Values.master.ports.rpc }}
    {{- else if $isRaftHa }}
    fs.jindofsx.namespace.rpc.address = {{ template "jindofs.fullname" . }}-master-0.{{ .Values.runtimeIdentity.namespace }}:{{ .Values.master.ports.rpc }},{{ template "jindofs.fullname" . }}-master-1.{{ .Values.runtimeIdentity.namespace }}:{{ .Values.master.ports.rpc }},{{ template "jindofs.fullname" . }}-master-2.{{ .Values.runtimeIdentity.namespace }}:{{ .Values.master.ports.rpc }}
    {{- end }}
    {{- range $key, $val := .Values.fuse.properties }}
    {{ $key }} = {{ $val }}
    {{- end }}
