apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluid-cluster-rolebinding
  namespace: fluid-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: fluid
  namespace: fluid-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluid
  namespace: fluid-system