# apiVersion: v1
# kind: Namespace
# metadata:
#   labels:
#     control-plane: controller
#   name: fluid-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataset-controller
  namespace: fluid-system
  labels:
    control-plane: dataset-controller
spec:
  selector:
    matchLabels:
      control-plane: dataset-controller
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: dataset-controller
    spec:
      serviceAccountName: dataset-controller
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: NotIn
                values:
                - virtual-kubelet
      tolerations:
      - operator: Exists
      #hostNetwork: true
      containers:
      - image: "{{ .Values.dataset.controller.image }}"
        name: manager
        command: ["dataset-controller", "start"]
        args:
          - --development=false
        env:
          {{- if .Values.workdir }}
          - name: FLUID_WORKDIR
            value: {{ .Values.workdir | quote }}
          {{- end }}
          {{- if .Values.runtime.alluxio.runtime.image }}
          - name: ALLUXIO_RUNTIME_IMAGE_ENV
            value: {{ .Values.runtime.alluxio.runtime.image | quote }}
          {{- end }}
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 200Mi
      terminationGracePeriodSeconds: 10
