---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goosefsruntime-controller
  namespace: {{ include "fluid.namespace" . }}
  labels:
    control-plane: goosefsruntime-controller
spec:
  selector:
    matchLabels:
      control-plane: goosefsruntime-controller
  {{ if .Values.runtime.goosefs.enabled -}}
  replicas: {{ .Values.runtime.goosefs.replicas }}
  {{- else }}
  replicas: 0
  {{- end }}
  template:
    metadata:
      labels:
        control-plane: goosefsruntime-controller
      annotations:
      {{ if gt (.Values.runtime.goosefs.replicas | int) 1 -}}
         controller.runtime.fluid.io/replicas: {{ .Values.runtime.goosefs.replicas | quote }}
      {{- end }}
    spec:
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: goosefsruntime-controller
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: NotIn
                values:
                - virtual-kubelet
      tolerations:
      - operator: Exists
      #hostNetwork: true
      containers:
      - image: "{{ .Values.runtime.goosefs.controller.image }}"
        imagePullPolicy: Always
        name: manager
        command: ["goosefsruntime-controller", "start"]
        args:
          - --development=false
          - --runtime-node-port-range={{ .Values.runtime.goosefs.portRange }}
          - --runtime-workers={{ .Values.runtime.goosefs.runtimeWorkers }}
          - --pprof-addr=:6060
          - --enable-leader-election
          - --leader-election-namespace={{ include "fluid.namespace" . }}
          - --port-allocate-policy={{ .Values.runtime.goosefs.portAllocatePolicy }}
        env:
          {{- if .Values.workdir }}
          - name: FLUID_WORKDIR
            value: {{ .Values.workdir | quote }}
          {{- end }}
          {{- if .Values.runtime.goosefs.init.image }}
          - name: DEFAULT_INIT_IMAGE_ENV
            value: {{ .Values.runtime.goosefs.init.image | quote }}
          {{- end }}
          {{- if .Values.runtime.goosefs.runtime.image }}
          - name: GOOSEFS_RUNTIME_IMAGE_ENV
            value: {{ .Values.runtime.goosefs.runtime.image | quote }}
          {{- end }}
          {{- if .Values.runtime.goosefs.fuse.image }}
          - name: GOOSEFS_FUSE_IMAGE_ENV
            value: {{ .Values.runtime.goosefs.fuse.image | quote }}
          {{- end }}
          {{- if .Values.runtime.mountRoot }}
          - name: MOUNT_ROOT
            value: {{ .Values.runtime.mountRoot | quote }}
          {{- end }}
          {{- if .Values.runtime.criticalFusePod }}
          - name: CRITICAL_FUSE_POD
            value: {{ ternary "true" "false" (semverCompare ">=1.16.0-0" .Capabilities.KubeVersion.Version) | quote }}
          {{- end }}
          {{- if .Values.runtime.syncRetryDuration }}
          - name: FLUID_SYNC_RETRY_DURATION
            value: {{ .Values.runtime.syncRetryDuration | quote }}
          {{- end }}
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 1536Mi
          requests:
            cpu: 100m
            memory: 200Mi
      terminationGracePeriodSeconds: 10
