{{ if .Values.runtime.jindo.enabled -}}
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: fluid-pod-admission-webhook
webhooks:
  - name: fluid-pod-admission-webhook
    rules:
      - apiGroups:   [""]
        apiVersions: ["v1"]
        operations:  ["CREATE"]
        resources:   ["pods"]
    clientConfig:
      service:
        namespace: fluid-system
        name: fluid-pod-admission-webhook
        path: "/mutate-v1-pod"
        port: 9443
      caBundle: Cg==
    timeoutSeconds: 20
    failurePolicy: Ignore
    namespaceSelector:
      matchLabels:
        Fluid-Injection: enabled
{{- end }}
