{{ if .Values.webhook.enabled -}}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: fluid-pod-admission-webhook
webhooks:
  - name: sidecar.fuse.fluid.io
    rules:
      - apiGroups:   [""]
        apiVersions: ["v1"]
        operations:  ["CREATE"]
        resources:   ["pods"]
    clientConfig:
      service:
        namespace: {{ include "fluid.namespace" . }}
        name: fluid-pod-admission-webhook
        path: "/mutate-fluid-io-v1alpha1-schedulepod"
        port: 9443
      caBundle: Cg==
    timeoutSeconds: {{ .Values.webhook.timeoutSeconds }}
    failurePolicy: Fail
    reinvocationPolicy: {{ .Values.webhook.reinvocationPolicy }}
    sideEffects: None
    admissionReviewVersions: ["v1","v1beta1"]
    objectSelector:
      matchLabels:
        serverless.fluid.io/inject: "true"
  - name: fuse.serverful.fluid.io
    rules:
      - apiGroups:   [""]
        apiVersions: ["v1"]
        operations:  ["CREATE"]
        resources:   ["pods"]
    clientConfig:
      service:
        namespace: {{ include "fluid.namespace" . }}
        name: fluid-pod-admission-webhook
        path: "/mutate-fluid-io-v1alpha1-schedulepod"
        port: 9443
      caBundle: Cg==
    timeoutSeconds: {{ .Values.webhook.timeoutSeconds }}
    failurePolicy: Fail
    reinvocationPolicy: {{ .Values.webhook.reinvocationPolicy }}
    sideEffects: None
    admissionReviewVersions: ["v1","v1beta1"]
    objectSelector:
      matchLabels:
        fuse.serverful.fluid.io/inject: "true"
{{- end }}
