{{- $masterCount := int .Values.master.replicaCount }}
{{- $isSingleMaster := eq $masterCount 1 }}
{{- $isRaftHa := eq $masterCount 3 }}

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "jindofs.fullname" . }}-worker
  labels:
    app: {{ template "jindofs.name" . }}
    chart: {{ template "jindofs.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: jindofs-worker
spec:
  selector:
    matchLabels:
      app: {{ template "jindofs.name" . }}
      release: {{ .Release.Name }}
      role: jindofs-worker
  template:
    metadata:
      labels:
        app: {{ template "jindofs.name" . }}
        chart: {{ template "jindofs.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        role: jindofs-worker
    spec:
      hostNetwork: {{ .Values.useHostNetwork }}
      hostPID: {{ .Values.useHostPID }}
      dnsPolicy: ClusterFirstWithHostNet
      securityContext:
        runAsUser: {{ .Values.user }}
        runAsGroup: {{ .Values.group }}
        fsGroup: {{ .Values.fsGroup }}
      nodeSelector:
{{- if .Values.worker.nodeSelector }}
{{ toYaml .Values.worker.nodeSelector | trim | indent 8  }}
{{- else if .Values.nodeSelector }}
{{ toYaml .Values.nodeSelector | trim | indent 8  }}
{{- end }}
      containers:
        - name: jindofs-worker
          image: {{ .Values.image }}:{{ .Values.imageTag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command: ["/entrypoint.sh"]
          args: ["worker"]
          env:
          {{- if $isSingleMaster }}
          - name: STORAGE_NAMESPACE_RPC_ADDRESS
            value: {{ template "jindofs.fullname" . }}-master-0:{{ .Values.master.ports.rpc }}
          - name: CLIENT_NAMESPACE_RPC_ADDRESS
            value: {{ template "jindofs.fullname" . }}-master-0:{{ .Values.master.ports.rpc }}
          {{- else if $isRaftHa }}
          - name: STORAGE_NAMESPACE_RPC_ADDRESS
            value: {{ template "jindofs.fullname" . }}-master-0:{{ .Values.master.ports.rpc }},{{ template "jindofs.fullname" . }}-master-1:{{ .Values.master.ports.rpc }},{{ template "jindofs.fullname" . }}-master-2:{{ .Values.master.ports.rpc }}
          - name: CLIENT_NAMESPACE_RPC_ADDRESS
            value: {{ template "jindofs.fullname" . }}-master-0:{{ .Values.master.ports.rpc }},{{ template "jindofs.fullname" . }}-master-1:{{ .Values.master.ports.rpc }},{{ template "jindofs.fullname" . }}-master-2:{{ .Values.master.ports.rpc }}
          {{- end }}
          {{- if .Values.fuse.runAs }}
          - name: RUN_AS_USER
            value: {{ .Values.fuse.runAs }}
          {{- end }}
          - name: STORAGE_ADDRESS
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          ports:
          - containerPort: {{ .Values.worker.ports.rpc }}
            name: rpc
          volumeMounts:
            - name: bigboot-config
              mountPath: /bigboot.cfg
              subPath: bigboot.cfg
            - name: bigboot-config
              mountPath: /hdfs-3.2.1/etc/hadoop/core-site.xml
              subPath: core-site.xml
          {{- range $name, $path := .Values.mounts.workersAndClients }}
            - name: datavolume-{{ $name }}
              mountPath: "{{ $path }}"
            {{- end }}
          {{- if .Values.hadoopConfig }}
          {{- if or .Values.hadoopConfig.includeCoreSite .Values.hadoopConfig.includeHdfsSite }}
            - name: hdfs-confs
              mountPath: /hdfs-site.xml
              subPath: hdfs-site.xml
          {{- end }}
          {{- end }}
          {{- if .Values.secret }}
            - name: jindofs-secret-token
              mountPath: /token
              readOnly: true
          {{- end }}
            - mountPath: /etc/localtime
              name: volume-localtime
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ''
          name: volume-localtime
          {{- range $name, $path := .Values.mounts.workersAndClients }}
        - hostPath:
            path:  "{{ $path }}"
            type: DirectoryOrCreate
          name: datavolume-{{ $name }}
          {{- end }}
        {{- if .Values.hadoopConfig }}
        {{- if or .Values.hadoopConfig.includeCoreSite .Values.hadoopConfig.includeHdfsSite }}
        - name: hdfs-confs
          configMap:
            name: {{ .Values.hadoopConfig.configMap }}
        {{- end }}
        {{- end }}
        {{- if .Values.secret }}
        - name: jindofs-secret-token
          secret:
            secretName: {{ .Values.secret }}
        {{- end }}
        - name: bigboot-config
          configMap:
            name: {{ template "jindofs.fullname" . }}-config
