# permissions for end users to edit dataloads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dataload-editor-role
rules:
- apiGroups:
  - data.fluid.io
  resources:
  - dataloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - data.fluid.io
  resources:
  - dataloads/status
  verbs:
  - get
