# permissions for end users to edit eacruntimes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eacruntime-editor-role
rules:
- apiGroups:
  - data.fluid.io
  resources:
  - eacruntimes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - data.fluid.io
  resources:
  - eacruntimes/status
  verbs:
  - get