# permissions for end users to view eacruntimes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eacruntime-viewer-role
rules:
- apiGroups:
  - data.fluid.io
  resources:
  - eacruntimes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - data.fluid.io
  resources:
  - eacruntimes/status
  verbs:
  - get