# permissions for end users to view efcruntimes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: efcruntimes-viewer-role
rules:
- apiGroups:
  - data.fluid.io
  resources:
  - efcruntimes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - data.fluid.io
  resources:
  - efcruntimes/status
  verbs:
  - get
