# permissions for end users to view juicefsruntimes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: juicefsruntime-viewer-role
rules:
- apiGroups:
  - data.fluid.io
  resources:
  - juicefsruntimes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - data.fluid.io
  resources:
  - juicefsruntimes/status
  verbs:
  - get
