# permissions for end users to view ThinRuntimeProfiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ThinRuntimeProfile-viewer-role
rules:
- apiGroups:
  - data.fluid.io
  resources:
  - ThinRuntimeProfiles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - data.fluid.io
  resources:
  - ThinRuntimeProfiles/status
  verbs:
  - get
