# permissions for end users to edit thinruntimes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: thinruntime-editor-role
rules:
- apiGroups:
  - data.fluid.io
  resources:
  - thinruntimes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - data.fluid.io
  resources:
  - thinruntimes/status
  verbs:
  - get
