apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "efc.fullname" . }}-worker
  labels:
    app: {{ template "efc.name" . }}
    chart: {{ template "efc.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: efc-worker
    fluid.io/dataset: {{ .Release.Namespace }}-{{ .Release.Name }}
    fluid.io/dataset-placement: {{ .Values.placement }}
  ownerReferences:
  {{- if .Values.owner.enabled }}
  - apiVersion: {{ .Values.owner.apiVersion }}
    blockOwnerDeletion: {{ .Values.owner.blockOwnerDeletion }}
    controller: {{ .Values.owner.controller }}
    kind: {{ .Values.owner.kind }}
    name: {{ .Values.owner.name }}
    uid: {{ .Values.owner.uid }}
  {{- end }}
spec:
  podManagementPolicy: "Parallel"
  replicas: {{ if .Values.worker.enabled -}} {{ $.Values.worker.count }} {{ else -}} 0 {{ end }}
  serviceName: {{ template "efc.fullname" . }}-worker
  selector:
    matchLabels:
      app: {{ template "efc.name" . }}
      release: {{ .Release.Name }}
      role: efc-worker
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      {{- if .Values.worker.annotations }}
      {{- range $key, $val := .Values.worker.annotations }}
        {{ $key | quote }}: {{ $val | quote }}
      {{- end }}
      {{- end }}
      labels:
        app: {{ template "efc.name" . }}
        chart: {{ template "efc.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        role: efc-worker
        fluid.io/dataset: {{ .Release.Namespace }}-{{ .Release.Name }}
        fluid.io/dataset-placement: {{ .Values.placement }}
        {{- if .Values.worker.labels }}
        {{- range $key, $val := .Values.worker.labels }}
        {{ $key | quote }}: {{ $val | quote }}
        {{- end }}
        {{- end }}
    spec:
      {{- if .Values.worker.hostNetwork }}
      hostNetwork: {{ .Values.worker.hostNetwork }}
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      nodeSelector:
      {{- if .Values.worker.nodeSelector }}
{{ toYaml .Values.worker.nodeSelector | trim | indent 8  }}
      {{- else if .Values.nodeSelector }}
{{ toYaml .Values.nodeSelector | trim | indent 8  }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      containers:
        - name: efc-worker
          image: {{ .Values.worker.image }}:{{ .Values.worker.imageTag }}
          imagePullPolicy: {{ .Values.worker.imagePullPolicy }}
          {{- if .Values.worker.resources  }}
          resources:
{{ toYaml .Values.worker.resources | trim | indent 12  }}
          {{- end }}
          command: [ "/entrypoint.sh" ]
          args:
            - "worker"
            - {{ .Values.worker.option | quote }}
          ports:
          - containerPort: {{ .Values.worker.port.rpc }}
            name: rpc
          volumeMounts:
            {{- if .Values.worker.tieredstore }}
{{- include "efc.tieredstoreVolumeMounts" .Values.worker }}
            {{- end }}
      {{- with .Values.worker.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.worker.tieredstore }}
{{- include "efc.tieredstoreVolumes" .Values.worker }}
        {{- end }}
