apiVersion: v1
entries:
  fluid:
  - apiVersion: v2
    appVersion: 0.5.0-ce65f9e
    created: "2021-04-01T10:52:51.4357435+08:00"
    description: A Helm chart to deploy fluid in Kubernetes
    digest: db0c166fa49e49b18a243dcf1e5d069aecf22d4a5ccc463098f687edb472b03f
    home: https://github.com/fluid-cloudnative/fluid
    keywords:
    - category:data
    - fluid
    - namespace:fluid-system
    - releaseName:fluid
    name: fluid
    type: application
    urls:
    - fluid-0.5.0.tgz
    version: 0.5.0
  - apiVersion: v2
    appVersion: 0.4.0
    created: "2021-04-01T10:52:51.4349967+08:00"
    description: A Helm chart to deploy fluid in Kubernetes
    digest: 3156cb1490b2b2de1f2a5588ef1919bfcffab182fe77063ec460310a67a07dd3
    name: fluid
    type: application
    urls:
    - fluid-0.4.0.tgz
    version: 0.4.0
  - apiVersion: v2
    appVersion: 0.3.0
    created: "2021-04-01T10:52:51.4344709+08:00"
    description: A Helm chart to deploy fluid in Kubernetes
    digest: 019ea93e8fd9928c07e7e862fa4b6e4ae234d92fa44652b3f3a2118b13908dfd
    name: fluid
    type: application
    urls:
    - fluid-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    appVersion: 0.2.0
    created: "2021-04-01T10:52:51.4339698+08:00"
    description: A Helm chart to deploy fluid in Kubernetes
    digest: 16a992edfc9bccd974cb4fc2f16471e06d422d92d3c3510d9b04511d373aa0f9
    name: fluid
    type: application
    urls:
    - fluid-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2021-04-01T10:52:51.4335477+08:00"
    description: A Helm chart to deploy fluid in Kubernetes
    digest: 5254da4a4548afb3dcb835554fa06f9ac4a794e7613339579179c10a13e2b873
    name: fluid
    type: application
    urls:
    - fluid-0.1.0.tgz
    version: 0.1.0
generated: "2021-04-01T10:52:51.4329499+08:00"
