name: ""

dataProcess:
  targetDataset: ""
  scriptProcessor:
    image: ""
    imagePullPolicy: IfNotPresent
    restartPolicy: Never
    command: []
    args: []
    envs: []
    volumes: []
    volumeMounts: []
  jobProcessor:
    podSpec: {}