---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alluxioruntime-controller
  namespace: {{ include "fluid.namespace" . }}
  labels:
    control-plane: alluxioruntime-controller
spec:
  selector:
    matchLabels:
      control-plane: alluxioruntime-controller
  {{ if .Values.runtime.alluxio.enabled -}}
  replicas: {{ .Values.runtime.alluxio.replicas }}
  {{- else }}
  replicas: 0
  {{- end }}
  template:
    metadata:
      labels:
        control-plane: alluxioruntime-controller
      annotations:
      {{ if gt (.Values.runtime.alluxio.replicas | int) 1 -}}
        controller.runtime.fluid.io/replicas: {{ .Values.runtime.alluxio.replicas | quote }}
      {{- end }}
    spec:
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: alluxioruntime-controller
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: NotIn
                values:
                - virtual-kubelet
      tolerations:
      - operator: Exists
      #hostNetwork: true
      containers:
      - image: "{{ .Values.runtime.alluxio.controller.image }}"
        name: manager
        command: ["alluxioruntime-controller", "start"]
        args:
          - --development=false
          - --runtime-node-port-range={{ .Values.runtime.alluxio.portRange }}
          - --runtime-workers={{ .Values.runtime.alluxio.runtimeWorkers }}
          - --pprof-addr=:6060
          - --enable-leader-election
          - --leader-election-namespace={{ include "fluid.namespace" . }}
          - --port-allocate-policy={{ .Values.runtime.alluxio.portAllocatePolicy }}
        env:
          {{- if .Values.workdir }}
          - name: FLUID_WORKDIR
            value: {{ .Values.workdir | quote }}
          {{- end }}
          {{- if .Values.runtime.alluxio.init.image }}
          - name: DEFAULT_INIT_IMAGE_ENV
            value: {{ .Values.runtime.alluxio.init.image | quote }}
          {{- end }}
          {{- if .Values.runtime.alluxio.runtime.image }}
          - name: ALLUXIO_RUNTIME_IMAGE_ENV
            value: {{ .Values.runtime.alluxio.runtime.image | quote }}
          {{- end }}
          {{- if .Values.runtime.alluxio.fuse.image }}
          - name: ALLUXIO_FUSE_IMAGE_ENV
            value: {{ .Values.runtime.alluxio.fuse.image | quote }}
          {{- end }}
          {{- if .Values.runtime.mountRoot }}
          - name: MOUNT_ROOT
            value: {{ .Values.runtime.mountRoot | quote }}
          {{- end }}
          {{- if .Values.runtime.criticalFusePod }}
          - name: CRITICAL_FUSE_POD
            value: {{ ternary "true" "false" (semverCompare ">=1.16.0-0" .Capabilities.KubeVersion.Version) | quote }}
          {{- end }}
          {{- if .Values.runtime.syncRetryDuration }}
          - name: FLUID_SYNC_RETRY_DURATION
            value: {{ .Values.runtime.syncRetryDuration | quote }}
          {{- end }}
          {{- if .Values.image.imagePullSecrets }}
          - name: IMAGE_PULL_SECRETS
            {{- $secretList := list }}
            {{- range .Values.image.imagePullSecrets }}
              {{- range $name,$v := . }}
                {{- $secretList = append $secretList $v }}
              {{- end }}
            {{- end }}
            value: {{ join "," $secretList | quote }}
          {{- end }}
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 1536Mi
          requests:
            cpu: 100m
            memory: 200Mi
      terminationGracePeriodSeconds: 10
