---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goosefsruntime-controller
  namespace: {{ include "fluid.namespace" . }}
  labels:
    control-plane: goosefsruntime-controller
spec:
  selector:
    matchLabels:
      control-plane: goosefsruntime-controller
  {{ if .Values.runtime.goosefs.enabled -}}
  replicas: {{ .Values.runtime.goosefs.replicas }}
  {{- else }}
  replicas: 0
  {{- end }}
  template:
    metadata:
      labels:
        control-plane: goosefsruntime-controller
      annotations:
      {{ if gt (.Values.runtime.goosefs.replicas | int) 1 -}}
         controller.runtime.fluid.io/replicas: {{ .Values.runtime.goosefs.replicas | quote }}
      {{- end }}
    spec:
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: goosefsruntime-controller
      {{ include "fluid.controlplane.affinity" . | nindent 6}}
      {{- if .Values.runtime.goosefs.tolerations }}
      tolerations:
{{ toYaml .Values.runtime.goosefs.tolerations | indent 6 }}
      {{- end }}
      #hostNetwork: true
      containers:
      - image: {{ include "fluid.controlplane.imageTransform" (list .Values.runtime.goosefs.controller.imagePrefix .Values.runtime.goosefs.controller.imageName .Values.runtime.goosefs.controller.imageTag . ) }}
        imagePullPolicy: Always
        name: manager
        command: ["goosefsruntime-controller", "start"]
        args:
          - --development=false
          - --runtime-node-port-range={{ .Values.runtime.goosefs.portRange }}
          - --runtime-workers={{ .Values.runtime.goosefs.runtimeWorkers }}
          - --kube-api-qps={{ .Values.runtime.goosefs.kubeClientQPS }}
          - --kube-api-burst={{ .Values.runtime.goosefs.kubeClientBurst }}
          - --pprof-addr=:6060
          - --enable-leader-election
          - --leader-election-namespace={{ include "fluid.namespace" . }}
          - --port-allocate-policy={{ .Values.runtime.goosefs.portAllocatePolicy }}
        env:
          {{- if .Values.workdir }}
          - name: FLUID_WORKDIR
            value: {{ .Values.workdir | quote }}
          {{- end }}
          {{- if .Values.runtime.goosefs.init.imageName }}
          - name: DEFAULT_INIT_IMAGE_ENV
            value: {{ include "fluid.runtime.imageTransform" (list .Values.runtime.goosefs.init.imagePrefix .Values.runtime.goosefs.init.imageName .Values.runtime.goosefs.init.imageTag . ) }}
          {{- end }}
          {{- if .Values.runtime.goosefs.runtime.imageName }}
          - name: GOOSEFS_RUNTIME_IMAGE_ENV
            value: {{ include "fluid.runtime.imageTransform" (list .Values.runtime.goosefs.runtime.imagePrefix .Values.runtime.goosefs.runtime.imageName .Values.runtime.goosefs.runtime.imageTag . ) }}
          {{- end }}
          {{- if .Values.runtime.goosefs.fuse.imageName }}
          - name: GOOSEFS_FUSE_IMAGE_ENV
            value: {{ include "fluid.runtime.imageTransform" (list .Values.runtime.goosefs.fuse.imagePrefix .Values.runtime.goosefs.fuse.imageName .Values.runtime.goosefs.fuse.imageTag . ) }}
          {{- end }}
          {{- if .Values.runtime.mountRoot }}
          - name: MOUNT_ROOT
            value: {{ .Values.runtime.mountRoot | quote }}
          {{- end }}
          {{- if .Values.runtime.criticalFusePod }}
          - name: CRITICAL_FUSE_POD
            value: {{ ternary "true" "false" (semverCompare ">=1.16.0-0" .Capabilities.KubeVersion.Version) | quote }}
          {{- end }}
          {{- if .Values.runtime.syncRetryDuration }}
          - name: FLUID_SYNC_RETRY_DURATION
            value: {{ .Values.runtime.syncRetryDuration | quote }}
          {{- end }}
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        resources:
          {{- include "fluid.controlplane.resources" (list $ .Values.runtime.goosefs.resources) | nindent 10 }}
      terminationGracePeriodSeconds: 10
