---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: juicefsruntime-controller
  namespace: {{ include "fluid.namespace" . }}
  labels:
    control-plane: juicefsruntime-controller
spec:
  selector:
    matchLabels:
      control-plane: juicefsruntime-controller
  {{ if .Values.runtime.juicefs.enabled -}}
  replicas: {{ .Values.runtime.juicefs.replicas }}
  {{- else }}
  replicas: 0
  {{- end }}
  template:
    metadata:
      labels:
        control-plane: juicefsruntime-controller
      annotations:
      {{ if gt (.Values.runtime.juicefs.replicas | int) 1 -}}
         controller.runtime.fluid.io/replicas: {{ .Values.runtime.juicefs.replicas | quote }}
      {{- end }}
    spec:
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: juicefsruntime-controller
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: NotIn
                values:
                - virtual-kubelet
      {{- if .Values.runtime.juicefs.tolerations }}
      tolerations:
{{ toYaml .Values.runtime.juicefs.tolerations | indent 6 }}
      {{- end }}
      #hostNetwork: true
      containers:
      - image: "{{ .Values.runtime.juicefs.controller.repo }}/{{ .Values.runtime.juicefs.controller.image }}:{{ .Values.runtime.juicefs.controller.tag }}"
        name: manager
        args:
          - --development=false
          - --pprof-addr=:6060
          - --enable-leader-election
          - --runtime-workers={{ .Values.runtime.juicefs.runtimeWorkers }}
          - --leader-election-namespace={{ include "fluid.namespace" . }}
        command: ["juicefsruntime-controller", "start"]
        env:
          {{- if .Values.image.imagePullSecrets }}
          - name: IMAGE_PULL_SECRETS
            {{- $secretList := list }}
            {{- range .Values.image.imagePullSecrets }}
              {{- range $name,$v := . }}
                {{- $secretList = append $secretList $v }}
              {{- end }}
            {{- end }}
            value: {{ join "," $secretList | quote }}
          {{- end }}
          {{- if .Values.runtime.juicefs.fuse.ceimage }}
          - name: JUICEFS_CE_IMAGE_ENV
            value: {{ .Values.runtime.juicefs.fuse.ceimage | quote }}
          {{- end }}
          {{- if .Values.runtime.juicefs.fuse.eeimage }}
          - name: JUICEFS_EE_IMAGE_ENV
            value: {{ .Values.runtime.juicefs.fuse.eeimage | quote }}
          {{- end }}
          {{- if .Values.runtime.mountRoot }}
          - name: MOUNT_ROOT
            value: {{ .Values.runtime.mountRoot | quote }}
          {{- end }}
          {{- if .Values.runtime.criticalFusePod }}
          - name: CRITICAL_FUSE_POD
            value: {{ ternary "true" "false" (semverCompare ">=1.16.0-0" .Capabilities.KubeVersion.Version) | quote }}
          {{- end }}
          {{- if .Values.runtime.syncRetryDuration }}
          - name: FLUID_SYNC_RETRY_DURATION
            value: {{ .Values.runtime.syncRetryDuration | quote }}
          {{- end }}
          - name: HELM_DRIVER
            value: {{ template "fluid.helmDriver" . }}
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 1536Mi
          requests:
            cpu: 100m
            memory: 200Mi
      terminationGracePeriodSeconds: 10
