---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thinruntime-controller
  namespace: {{ include "fluid.namespace" . }}
  labels:
    control-plane: thinruntime-controller
spec:
  selector:
    matchLabels:
      control-plane: thinruntime-controller
  {{ if .Values.runtime.thin.enabled -}}
  replicas: {{ .Values.runtime.thin.replicas }}
  {{- else }}
  replicas: 0
  {{- end }}
  template:
    metadata:
      labels:
        control-plane: thinruntime-controller
      annotations:
      {{ if gt (.Values.runtime.thin.replicas | int) 1 -}}
        controller.runtime.fluid.io/replicas: {{ .Values.runtime.thin.replicas | quote }}
      {{- end }}
    spec:
      serviceAccountName: thinruntime-controller
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: NotIn
                    values:
                      - virtual-kubelet
      {{- if .Values.runtime.thin.tolerations }}
      tolerations:
{{ toYaml .Values.runtime.thin.tolerations | indent 6 }}
      {{- end }}
      #hostNetwork: true
      containers:
        - image: {{ include "fluid.controlplane.imageTransform" (list .Values.runtime.thin.controller.imagePrefix .Values.runtime.thin.controller.imageName .Values.runtime.thin.controller.imageTag . ) }}
          name: manager
          args:
            - --development=false
            - --pprof-addr=:6060
            - --enable-leader-election
            - --leader-election-namespace={{ include "fluid.namespace" . }}
          command: ["thinruntime-controller", "start"]
          env:
            {{- if .Values.runtime.mountRoot }}
            - name: MOUNT_ROOT
              value: {{ .Values.runtime.mountRoot | quote }}
            {{- end }}
            {{- if .Values.runtime.criticalFusePod }}
            - name: CRITICAL_FUSE_POD
              value: {{ ternary "true" "false" (semverCompare ">=1.16.0-0" .Capabilities.KubeVersion.Version) | quote }}
            {{- end }}
            {{- if .Values.runtime.syncRetryDuration }}
            - name: FLUID_SYNC_RETRY_DURATION
              value: {{ .Values.runtime.syncRetryDuration | quote }}
            {{- end }}
            - name: HELM_DRIVER
              value: {{ template "fluid.helmDriver" . }}
            - name: THIN_FUSE_CONFIG_STORAGE
              value: {{ .Values.runtime.thin.fuse.configStorage }}
          ports:
            - containerPort: 8080
              name: metrics
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 1536Mi
            requests:
              cpu: 100m
              memory: 200Mi
      terminationGracePeriodSeconds: 10
