---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dataset-controller
rules:
  - apiGroups:
      - data.fluid.io
    resources:
      - dataloads
      - dataloads/status
      - datasets
      - datasets/status
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dataset-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dataset-controller
subjects:
- kind: ServiceAccount
  name: dataset-controller
  namespace: fluid-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dataset-controller
  namespace: fluid-system
