{{ if .Values.crdUpgrade.enabled -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ include "fluid.namespace" . }}
  name: fluid-crds-upgrade-{{ replace "." "" .Chart.AppVersion }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
{{- if .Values.crdUpgrade.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ .Values.crdUpgrade.ttlSecondsAfterFinished }}
{{- end }}
  template:
    spec:
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.crdUpgrade.tolerations }}
      tolerations:
{{ toYaml .Values.crdUpgrade.tolerations | indent 6 }}
      {{- end }}
      serviceAccountName: fluid-crds-upgrade
      containers:
        - name: fluid-crds-upgrade
          image: {{ include "fluid.controlplane.imageTransform" (list .Values.crdUpgrade.imagePrefix .Values.crdUpgrade.imageName .Values.crdUpgrade.imageTag . ) }}
          imagePullPolicy: IfNotPresent
          command: ["bash", "/fluid/upgrade-crds.sh"]
      restartPolicy: OnFailure
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluid-crds-upgrade
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create", "get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluid-crds-upgrade
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluid-crds-upgrade
subjects:
  - kind: ServiceAccount
    name: fluid-crds-upgrade
    namespace: {{ include "fluid.namespace" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluid-crds-upgrade
  namespace: {{ include "fluid.namespace" . }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
{{- end }}
