{{ if .Values.runtime.alluxio.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alluxioruntime-controller
  namespace: fluid-system
  labels:
    control-plane: alluxioruntime-controller
spec:
  selector:
    matchLabels:
      control-plane: alluxioruntime-controller
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: alluxioruntime-controller
    spec:
      serviceAccountName: alluxioruntime-controller
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: NotIn
                values:
                - virtual-kubelet
      tolerations:
      - operator: Exists
      #hostNetwork: true
      containers:
      - image: "{{ .Values.runtime.alluxio.controller.image }}"
        name: manager
        command: ["alluxioruntime-controller", "start"]
        args:
          - --development=false
          - --runtime-node-port-range={{ .Values.runtime.alluxio.portRange }}
          - --runtime-workers={{ .Values.runtime.alluxio.runtimeWorkers }}
        env:
          {{- if .Values.workdir }}
          - name: FLUID_WORKDIR
            value: {{ .Values.workdir | quote }}
          {{- end }}
          {{- if .Values.runtime.alluxio.init.image }}
          - name: DEFAULT_INIT_IMAGE_ENV
            value: {{ .Values.runtime.alluxio.init.image | quote }}
          {{- end }}
          {{- if .Values.runtime.alluxio.runtime.image }}
          - name: ALLUXIO_RUNTIME_IMAGE_ENV
            value: {{ .Values.runtime.alluxio.runtime.image | quote }}
          {{- end }}
          {{- if .Values.runtime.alluxio.fuse.image }}
          - name: ALLUXIO_FUSE_IMAGE_ENV
            value: {{ .Values.runtime.alluxio.fuse.image | quote }}
          {{- end }}
          {{- if .Values.runtime.mountRoot }}
          - name: MOUNT_ROOT
            value: {{ .Values.runtime.mountRoot | quote }}
          {{- end }}
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 1536Mi
          requests:
            cpu: 100m
            memory: 200Mi
      terminationGracePeriodSeconds: 10
{{- end }}
