
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alluxioruntime-controller
  namespace: fluid-system
  labels:
    control-plane: alluxioruntime-controller
spec:
  selector:
    matchLabels:
      control-plane: alluxioruntime-controller
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: alluxioruntime-controller
    spec:
      serviceAccountName: alluxioruntime-controller
      tolerations:
      - operator: Exists
      hostNetwork: true
      containers:
      - image: "{{ .Values.runtime.alluxio.controller.image }}"
        name: manager
        command: ["alluxioruntime-controller", "start"]
        args:
          - --development=false
        env:
          {{- if .Values.runtime.alluxio.init.image }}
          - name: ALLUXIO_INIT_IMAGE_ENV
            value: {{ .Values.runtime.alluxio.init.image | quote }}
          {{- end }}
          {{- if .Values.runtime.mountRoot }}
          - name: MOUNT_ROOT
            value: {{ .Values.runtime.mountRoot | quote }}
          {{- end }}
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 200Mi
      terminationGracePeriodSeconds: 10
