{{- $masterCount := int .Values.master.replicaCount }}
{{- $isSingleMaster := eq $masterCount 1 }}
{{- $isRaftHa := eq $masterCount 3 }}
{{- $notEnableDnsConfig := (eq .Values.master.dnsServer "1.1.1.1") }}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "jindofs.fullname" . }}-master
  labels:
    name: {{ template "jindofs.fullname" . }}-master
    app: {{ template "jindofs.name" . }}
    chart: {{ template "jindofs.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: jindofs-master
    {{- include "library.fluid.labels" . | nindent 4 }}
  ownerReferences:
  {{- if .Values.owner.enabled }}
  - apiVersion: {{ .Values.owner.apiVersion }}
    blockOwnerDeletion: {{ .Values.owner.blockOwnerDeletion }}
    controller: {{ .Values.owner.controller }}
    kind: {{ .Values.owner.kind }}
    name: {{ .Values.owner.name }}
    uid: {{ .Values.owner.uid }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ template "jindofs.name" . }}
      role: jindofs-master
      name: {{ template "jindofs.fullname" . }}-master
  serviceName: "jindofs-master"
  replicas: {{ $masterCount }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        name: {{ template "jindofs.fullname" . }}-master
        app: {{ template "jindofs.name" . }}
        chart: {{ template "jindofs.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        role: jindofs-master
{{- if .Values.labels }}
{{ toYaml .Values.labels | trim | indent 8 }}
{{- end }}
{{- if .Values.master.labels }}
{{ toYaml .Values.master.labels | trim | indent 8 }}
{{- end }}
    spec:
      {{- if .Values.master.imagePullSecrets }}
      imagePullSecrets:
{{- toYaml .Values.master.imagePullSecrets | nindent 8 }}
      {{- else if .Values.imagePullSecrets }}
      imagePullSecrets:
{{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      hostNetwork: {{ .Values.useHostNetwork }}
      nodeSelector:
{{- if .Values.master.nodeSelector }}
{{ toYaml .Values.master.nodeSelector | trim | indent 8  }}
{{- else if .Values.nodeSelector }}
{{ toYaml .Values.nodeSelector | trim | indent 8  }}
{{- end }}
     {{- if .Values.master.tolerations }}
      tolerations:
{{ toYaml .Values.master.tolerations | indent 8 }}
     {{- end }}
      securityContext:
        runAsUser: {{ .Values.user }}
        runAsGroup: {{ .Values.group }}
        fsGroup: {{ .Values.fsGroup }}
      initContainers:
        {{ if .Values.initPortCheck.enabled -}}
        - name: init-port-check
          image: {{ .Values.initPortCheck.image }}:{{ .Values.initPortCheck.imageTag }}
          imagePullPolicy: {{ .Values.initPortCheck.imagePullPolicy }}
          securityContext:
            privileged: true
          command: ["/entrypoint.sh"]
          args:
            - "check_port"
          env:
            - name: PORTS_TO_CHECK
              value: {{ .Values.initPortCheck.portsToCheck | quote }}
      {{- end }}
      containers:
        - name: jindofs-master
          image: {{ .Values.image }}:{{ .Values.imageTag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          {{- if .Values.master.resources }}
          resources:
            limits:
            {{- if .Values.master.resources }}
            {{- if .Values.master.resources.limits }}
            {{- if .Values.master.resources.limits.cpu }}
              cpu: {{ .Values.master.resources.limits.cpu }}
              memory: {{ .Values.master.resources.limits.memory }}
            {{- end }}
            {{- end }}
            requests:
            {{- if .Values.master.resources.requests }}
            {{- if .Values.master.resources.requests.cpu }}
              cpu: {{ .Values.master.resources.requests.cpu }}
              memory: {{ .Values.master.resources.requests.memory }}
            {{- end }}
            {{- end }}
            {{- end }}
          {{- end }}
          command: ["/entrypoint.sh"]
          args: ["master"]
          env:
          {{- if $isSingleMaster }}
          - name: CLIENT_NAMESPACE_RPC_ADDRESS
            value: {{ template "jindofs.fullname" . }}-master-0:{{ .Values.master.ports.rpc }}
          - name: NAMESPACE_BACKEND_RAFT_HOSTNAME
            value: {{ template "jindofs.fullname" . }}-master-0
          {{- else if $isRaftHa }}
          - name: CLIENT_NAMESPACE_RPC_ADDRESS
            value: {{ template "jindofs.fullname" . }}-master-0:{{ .Values.master.ports.rpc }},{{ template "jindofs.fullname" . }}-master-1:{{ .Values.master.ports.rpc }},{{ template "jindofs.fullname" . }}-master-2:{{ .Values.master.ports.rpc }}
          - name: NAMESPACE_BACKEND_RAFT_INITIAL_CONF
            value: {{ template "jindofs.fullname" . }}-master-0:{{ .Values.master.ports.raft }}:0,{{ template "jindofs.fullname" . }}-master-1:{{ .Values.master.ports.raft }}:0,{{ template "jindofs.fullname" . }}-master-2:{{ .Values.master.ports.raft }}:0
          - name: NAMESPACE_BACKEND_RAFT_HOSTNAME
            value: {{ template "jindofs.fullname" . }}-master-0,{{ template "jindofs.fullname" . }}-master-1,{{ template "jindofs.fullname" . }}-master-2
          {{- end }}
          {{- if .Values.fuse.runAs }}
          - name: RUN_AS_USER
            value: {{ .Values.fuse.runAs }}
          {{- end }}
          ports:
          - containerPort: {{ .Values.master.ports.rpc }}
            name: rpc
          {{- if $isRaftHa }}
          - containerPort: {{ .Values.master.ports.raft }}
            name: raft
          {{- end }}
          volumeMounts:
            - name: bigboot-config
              mountPath: /bigboot.cfg
              subPath: bigboot.cfg
            - name: bigboot-config
              mountPath: /hdfs-3.2.1/etc/hadoop/core-site.xml
              subPath: core-site.xml
          {{- range $name, $path := .Values.mounts.master }}
            - name: datavolume-{{ $name }}
              mountPath: "{{ $path }}"
          {{- end }}
          {{- if .Values.hadoopConfig }}
          {{- if or .Values.hadoopConfig.includeCoreSite .Values.hadoopConfig.includeHdfsSite }}
            - name: hdfs-confs
              mountPath: /hdfs-site.xml
              subPath: hdfs-site.xml
          {{- end }}
          {{- end }}
          {{- if .Values.secret }}
            - name: jindofs-secret-token
              mountPath: /token
              readOnly: true
          {{- end }}
            - mountPath: /etc/localtime
              name: volume-localtime
      restartPolicy: Always
      {{- if $notEnableDnsConfig }}
      dnsPolicy: {{ .Values.useHostNetwork | ternary "ClusterFirstWithHostNet" "ClusterFirst" }}
      {{- else }}
      dnsConfig:
        nameservers:
        - {{ .Values.master.dnsServer }}
        options:
        - name: ndots
          value: "5"
        searches:
        - {{ .Values.master.namespace }}.svc.cluster.local
        - svc.cluster.local
        - cluster.local
        - tbsite.net
        - aliyun.com
      dnsPolicy: None
      enableServiceLinks: false
      {{- end }}
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ''
          name: volume-localtime
          {{- range $name, $path := .Values.mounts.master }}
        - hostPath:
            path:  "{{ $path }}"
            type: DirectoryOrCreate
          name: datavolume-{{ $name }}
          {{- end }}
        {{- if .Values.hadoopConfig }}
        {{- if or .Values.hadoopConfig.includeCoreSite .Values.hadoopConfig.includeHdfsSite }}
        - name: hdfs-confs
          configMap:
            name: {{ .Values.hadoopConfig.configMap }}
        {{- end }}
        {{- end }}
        {{- if .Values.secret }}
        - name: jindofs-secret-token
          secret:
            secretName: {{ .Values.secret }}
        {{- end }}
        - name: bigboot-config
          configMap:
            name: {{ template "jindofs.fullname" . }}-config
