
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.3.0
  creationTimestamp: null
  name: datasets.data.fluid.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.ufsTotal
    name: Ufs Total Size
    type: string
  - JSONPath: .status.cacheStates.cached
    name: Cached
    type: string
  - JSONPath: .status.cacheStates.cacheCapacity
    name: Cache Capacity
    type: string
  - JSONPath: .status.cacheStates.cachedPercentage
    name: Cached Percentage
    type: string
  - JSONPath: .status.phase
    name: Phase
    type: string
  - JSONPath: .status.hcfs.endpoint
    name: HCFS URL
    priority: 10
    type: string
  - JSONPath: .status.fileNum
    name: TOTAL FILES
    priority: 11
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: data.fluid.io
  names:
    kind: Dataset
    listKind: DatasetList
    plural: datasets
    singular: dataset
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Dataset is the Schema for the datasets API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: DatasetSpec defines the desired state of Dataset
          properties:
            accessModes:
              description: AccessModes contains all ways the volume backing the PVC
                can be mounted
              items:
                type: string
              type: array
            mounts:
              description: Mount Points to be mounted on Alluxio.
              items:
                description: Mount describes a mounting. <br> Refer to <a href="https://docs.alluxio.io/os/user/stable/en/ufs/S3.html">Alluxio
                  Storage Integrations</a> for more info
                properties:
                  mountPoint:
                    description: MountPoint is the mount point of source.
                    minLength: 10
                    type: string
                  name:
                    description: The name of mount
                    minLength: 0
                    type: string
                  options:
                    additionalProperties:
                      type: string
                    description: The Mount Options. <br> Refer to <a href="https://docs.alluxio.io/os/user/stable/en/reference/Properties-List.html">Mount
                      Options</a>.  <br> The option has Prefix 'fs.' And you can Learn
                      more from <a href="https://docs.alluxio.io/os/user/stable/en/ufs/S3.html">The
                      Storage Integrations</a>
                    type: object
                  path:
                    description: The path of mount, if not set will be /{Name}
                    type: string
                  readOnly:
                    description: 'Optional: Defaults to false (read-write).'
                    type: boolean
                  shared:
                    description: 'Optional: Defaults to false (shared).'
                    type: boolean
                type: object
              minItems: 1
              type: array
            nodeAffinity:
              description: NodeAffinity defines constraints that limit what nodes
                this dataset can be cached to. This field influences the scheduling
                of pods that use the cached dataset.
              properties:
                required:
                  description: Required specifies hard node constraints that must
                    be met.
                  properties:
                    nodeSelectorTerms:
                      description: Required. A list of node selector terms. The terms
                        are ORed.
                      items:
                        description: A null or empty node selector term matches no
                          objects. The requirements of them are ANDed. The TopologySelectorTerm
                          type implements a subset of the NodeSelectorTerm.
                        properties:
                          matchExpressions:
                            description: A list of node selector requirements by node's
                              labels.
                            items:
                              description: A node selector requirement is a selector
                                that contains values, a key, and an operator that
                                relates the key and values.
                              properties:
                                key:
                                  description: The label key that the selector applies
                                    to.
                                  type: string
                                operator:
                                  description: Represents a key's relationship to
                                    a set of values. Valid operators are In, NotIn,
                                    Exists, DoesNotExist. Gt, and Lt.
                                  type: string
                                values:
                                  description: An array of string values. If the operator
                                    is In or NotIn, the values array must be non-empty.
                                    If the operator is Exists or DoesNotExist, the
                                    values array must be empty. If the operator is
                                    Gt or Lt, the values array must have a single
                                    element, which will be interpreted as an integer.
                                    This array is replaced during a strategic merge
                                    patch.
                                  items:
                                    type: string
                                  type: array
                              required:
                              - key
                              - operator
                              type: object
                            type: array
                          matchFields:
                            description: A list of node selector requirements by node's
                              fields.
                            items:
                              description: A node selector requirement is a selector
                                that contains values, a key, and an operator that
                                relates the key and values.
                              properties:
                                key:
                                  description: The label key that the selector applies
                                    to.
                                  type: string
                                operator:
                                  description: Represents a key's relationship to
                                    a set of values. Valid operators are In, NotIn,
                                    Exists, DoesNotExist. Gt, and Lt.
                                  type: string
                                values:
                                  description: An array of string values. If the operator
                                    is In or NotIn, the values array must be non-empty.
                                    If the operator is Exists or DoesNotExist, the
                                    values array must be empty. If the operator is
                                    Gt or Lt, the values array must have a single
                                    element, which will be interpreted as an integer.
                                    This array is replaced during a strategic merge
                                    patch.
                                  items:
                                    type: string
                                  type: array
                              required:
                              - key
                              - operator
                              type: object
                            type: array
                        type: object
                      type: array
                  required:
                  - nodeSelectorTerms
                  type: object
              type: object
            owner:
              description: The owner of the dataset
              properties:
                gid:
                  description: The gid to run the alluxio runtime
                  format: int64
                  type: integer
                group:
                  description: The group name to run the alluxio runtime
                  type: string
                uid:
                  description: The uid to run the alluxio runtime
                  format: int64
                  type: integer
                user:
                  description: The user name to run the alluxio runtime
                  type: string
              required:
              - gid
              - group
              - uid
              - user
              type: object
            runtimes:
              description: Runtimes for supporting dataset (e.g. AlluxioRuntime)
              items:
                description: Runtime describes a runtime to be used to support dataset
                properties:
                  category:
                    description: Category the runtime object belongs to (e.g. Accelerate)
                    type: string
                  name:
                    description: Name of the runtime object
                    type: string
                  namespace:
                    description: Namespace of the runtime object
                    type: string
                  type:
                    description: Runtime object's type (e.g. Alluxio)
                    type: string
                type: object
              type: array
          type: object
        status:
          description: DatasetStatus defines the observed state of Dataset
          properties:
            cacheStates:
              additionalProperties:
                type: string
              description: CacheStatus represents the total resources of the dataset.
              type: object
            conditions:
              description: Conditions is an array of current observed conditions.
              items:
                description: Condition describes the state of the cache at a certain
                  point.
                properties:
                  lastTransitionTime:
                    description: Last time the condition transitioned from one status
                      to another.
                    format: date-time
                    type: string
                  lastUpdateTime:
                    description: The last time this condition was updated.
                    format: date-time
                    type: string
                  message:
                    description: A human readable message indicating details about
                      the transition.
                    type: string
                  reason:
                    description: The reason for the condition's last transition.
                    type: string
                  status:
                    description: Status of the condition, one of True, False, Unknown.
                    type: string
                  type:
                    description: Type of cache condition.
                    type: string
                required:
                - status
                - type
                type: object
              type: array
            dataLoadRef:
              description: DataLoadRef specifies the running DataLoad job that targets
                this Dataset. This is mainly used as a lock to prevent concurrent
                DataLoad jobs.
              type: string
            fileNum:
              description: FileNum represents the file numbers of the dataset
              type: string
            hcfs:
              description: HCFSStatus represents hcfs info
              properties:
                endpoint:
                  description: Endpoint for accessing
                  type: string
                underlayerFileSystemVersion:
                  description: Underlayer HCFS Compatible Version
                  type: string
              type: object
            phase:
              description: 'Dataset Phase. One of the four phases: `Pending`, `Bound`,
                `NotBound` and `Failed`'
              type: string
            runtimes:
              description: Runtimes for supporting dataset
              items:
                description: Runtime describes a runtime to be used to support dataset
                properties:
                  category:
                    description: Category the runtime object belongs to (e.g. Accelerate)
                    type: string
                  name:
                    description: Name of the runtime object
                    type: string
                  namespace:
                    description: Namespace of the runtime object
                    type: string
                  type:
                    description: Runtime object's type (e.g. Alluxio)
                    type: string
                type: object
              type: array
            ufsTotal:
              description: Total in GB of dataset in the cluster
              type: string
          required:
          - conditions
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
