apiVersion: v2
name: efc
description: A fuse filesystem for NAS with distributed cache.
version: 0.1.4
maintainers:
  - name: Yingchun Ma
    email: mayingchun.myc@alibaba-inc.com
  - name: Yi Zhan
    email: hanson.yj@alibaba-inc.com

dependencies:
- name: library
  version: "0.2.0"
  repository: "file://../library"
